<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class InsertCountriesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        DB::table('countries')->delete();
        $countries = $this->getCountriesArray();
        $date = date("Y-m-d H:i:s");
        $countries_data = [];
        foreach($countries as $country) {
           $countries_data[] = [
                'name' => $country[1],
                'iso_code' => $country[2],
                'isd_code' => $country[3],
                'created_at' => $date,
                'updated_at' => $date
            ];
        }
       
       DB::table('countries')->insert($countries_data);
       echo count($countries_data)." countries inserted";
    }


    function getCountriesArray()
    {
       return array(
            array(1, 'Afghanistan', 'AF', '93'),
            array(2, 'Albania', 'AL', '355'),
            array(3, 'Algeria', 'DZ', '213'),
            array(4, 'American Samoa', 'AS', '1-684'),
            array(5, 'Andorra', 'AD', '376'),
            array(6, 'Angola', 'AO', '244'),
            array(7, 'Anguilla', 'AI', '1-264'),
            array(8, 'Antarctica', 'AQ', '672'),
            array(9, 'Antigua and Barbuda', 'AG', '1-268'),
            array(10, 'Argentina', 'AR', '54'),
            array(11, 'Armenia', 'AM', '374'),
            array(12, 'Aruba', 'AW', '297'),
            array(13, 'Australia', 'AU', '61'),
            array(14, 'Austria', 'AT', '43'),
            array(15, 'Azerbaijan', 'AZ', '994'),
            array(16, 'Bahamas', 'BS', '1-242'),
            array(17, 'Bahrain', 'BH', '973'),
            array(18, 'Bangladesh', 'BD', '880'),
            array(19, 'Barbados', 'BB', '1-246'),
            array(20, 'Belarus', 'BY', '375'),
            array(21, 'Belgium', 'BE', '32'),
            array(22, 'Belize', 'BZ', '501'),
            array(23, 'Benin', 'BJ', '229'),
            array(24, 'Bermuda', 'BM', '1-441'),
            array(25, 'Bhutan', 'BT', '975'),
            array(26, 'Bolivia', 'BO', '591'),
            array(27, 'Bosnia and Herzegowina', 'BA', '387'),
            array(28, 'Botswana', 'BW', '267'),
            array(29, 'Bouvet Island', 'BV', '47'),
            array(30, 'Brazil', 'BR', '55'),
            array(31, 'British Indian Ocean Territory', 'IO', '246'),
            array(32, 'Brunei Darussalam', 'BN', '673'),
            array(33, 'Bulgaria', 'BG', '359'),
            array(34, 'Burkina Faso', 'BF', '226'),
            array(35, 'Burundi', 'BI', '257'),
            array(36, 'Cambodia', 'KH', '855'),
            array(37, 'Cameroon', 'CM', '237'),
            array(38, 'Canada', 'CA', '1'),
            array(39, 'Cape Verde', 'CV', '238'),
            array(40, 'Cayman Islands', 'KY', '1-345'),
            array(41, 'Central African Republic', 'CF', '236'),
            array(42, 'Chad', 'TD', '235'),
            array(43, 'Chile', 'CL', '56'),
            array(44, 'China', 'CN', '86'),
            array(45, 'Christmas Island', 'CX', '61'),
            array(46, 'Cocos (Keeling) Islands', 'CC', '61'),
            array(47, 'Colombia', 'CO', '57'),
            array(48, 'Comoros', 'KM', '269'),
            array(49, 'Congo Democratic Republic of', 'CG', '242'),
            array(50, 'Cook Islands', 'CK', '682'),
            array(51, 'Costa Rica', 'CR', '506'),
            array(52, "Cote D'Ivoire", 'CI', '225'),
            array(53, 'Croatia', 'HR', '385'),
            array(54, 'Cuba', 'CU', '53'),
            array(55, 'Cyprus', 'CY', '357'),
            array(56, 'Czech Republic', 'CZ', '420'),
            array(57, 'Denmark', 'DK', '45'),
            array(58, 'Djibouti', 'DJ', '253'),
            array(59, 'Dominica', 'DM', '1-767'),
            array(60, 'Dominican Republic', 'DO', '1-809'),
            array(61, 'Timor-Leste', 'TL', '670'),
            array(62, 'Ecuador', 'EC', '593'),
            array(63, 'Egypt', 'EG', '20'),
            array(64, 'El Salvador', 'SV', '503'),
            array(65, 'Equatorial Guinea', 'GQ', '240'),
            array(66, 'Eritrea', 'ER', '291'),
            array(67, 'Estonia', 'EE', '372'),
            array(68, 'Ethiopia', 'ET', '251'),
            array(69, 'Falkland Islands (Malvinas)', 'FK', '500'),
            array(70, 'Faroe Islands', 'FO', '298'),
            array(71, 'Fiji', 'FJ', '679'),
            array(72, 'Finland', 'FI', '358'),
            array(73, 'France', 'FR', '33'),
            array(75, 'French Guiana', 'GF', '594'),
            array(76, 'French Polynesia', 'PF', '689'),
            array(77, 'French Southern Territories', 'TF', NULL),
            array(78, 'Gabon', 'GA', '241'),
            array(79, 'Gambia', 'GM', '220'),
            array(80, 'Georgia', 'GE', '995'),
            array(81, 'Germany', 'DE', '49'),
            array(82, 'Ghana', 'GH', '233'),
            array(83, 'Gibraltar', 'GI', '350'),
            array(84, 'Greece', 'GR', '30'),
            array(85, 'Greenland', 'GL', '299'),
            array(86, 'Grenada', 'GD', '1-473'),
            array(87, 'Guadeloupe', 'GP', '590'),
            array(88, 'Guam', 'GU', '1-671'),
            array(89, 'Guatemala', 'GT', '502'),
            array(90, 'Guinea', 'GN', '224'),
            array(91, 'Guinea-bissau', 'GW', '245'),
            array(92, 'Guyana', 'GY', '592'),
            array(93, 'Haiti', 'HT', '509'),
            array(94, 'Heard Island and McDonald Islands', 'HM', '011'),
            array(95, 'Honduras', 'HN', '504'),
            array(96, 'Hong Kong', 'HK', '852'),
            array(97, 'Hungary', 'HU', '36'),
            array(98, 'Iceland', 'IS', '354'),
            array(99, 'India', 'IN', '91'),
            array(100, 'Indonesia', 'ID', '62'),
            array(101, 'Iran (Islamic Republic of)', 'IR', '98'),
            array(102, 'Iraq', 'IQ', '964'),
            array(103, 'Ireland', 'IE', '353'),
            array(104, 'Israel', 'IL', '972'),
            array(105, 'Italy', 'IT', '39'),
            array(106, 'Jamaica', 'JM', '1-876'),
            array(107, 'Japan', 'JP', '81'),
            array(108, 'Jordan', 'JO', '962'),
            array(109, 'Kazakhstan', 'KZ', '7'),
            array(110, 'Kenya', 'KE', '254'),
            array(111, 'Kiribati', 'KI', '686'),
            array(112, "Korea, Democratic People's Republic of", 'KP', '850'),
            array(113, 'South Korea', 'KR', '82'),
            array(114, 'Kuwait', 'KW', '965'),
            array(115, 'Kyrgyzstan', 'KG', '996'),
            array(116, "Lao People's Democratic Republic", 'LA', '856'),
            array(117, 'Latvia', 'LV', '371'),
            array(118, 'Lebanon', 'LB', '961'),
            array(119, 'Lesotho', 'LS', '266'),
            array(120, 'Liberia', 'LR', '231'),
            array(121, 'Libya', 'LY', '218'),
            array(122, 'Liechtenstein', 'LI', '423'),
            array(123, 'Lithuania', 'LT', '370'),
            array(124, 'Luxembourg', 'LU', '352'),
            array(125, 'Macao', 'MO', '853'),
            array(126, 'Macedonia, The Former Yugoslav Republic of', 'MK', '389'),
            array(127, 'Madagascar', 'MG', '261'),
            array(128, 'Malawi', 'MW', '265'),
            array(129, 'Malaysia', 'MY', '60'),
            array(130, 'Maldives', 'MV', '960'),
            array(131, 'Mali', 'ML', '223'),
            array(132, 'Malta', 'MT', '356'),
            array(133, 'Marshall Islands', 'MH', '692'),
            array(134, 'Martinique', 'MQ', '596'),
            array(135, 'Mauritania', 'MR', '222'),
            array(136, 'Mauritius', 'MU', '230'),
            array(137, 'Mayotte', 'YT', '262'),
            array(138, 'Mexico', 'MX', '52'),
            array(139, 'Micronesia, Federated States of', 'FM', '691'),
            array(140, 'Moldova', 'MD', '373'),
            array(141, 'Monaco', 'MC', '377'),
            array(142, 'Mongolia', 'MN', '976'),
            array(143, 'Montserrat', 'MS', '1-664'),
            array(144, 'Morocco', 'MA', '212'),
            array(145, 'Mozambique', 'MZ', '258'),
            array(146, 'Myanmar', 'MM', '95'),
            array(147, 'Namibia', 'NA', '264'),
            array(148, 'Nauru', 'NR', '674'),
            array(149, 'Nepal', 'NP', '977'),
            array(150, 'Netherlands', 'NL', '31'),
            array(151, 'Netherlands Antilles', 'AN', '599'),
            array(152, 'New Caledonia', 'NC', '687    '),
            array(153, 'New Zealand', 'NZ', '64'),
            array(154, 'Nicaragua', 'NI', '505'),
            array(155, 'Niger', 'NE', '227'),
            array(156, 'Nigeria', 'NG', '234'),
            array(157, 'Niue', 'NU', '683'),
            array(158, 'Norfolk Island', 'NF', '672'),
            array(159, 'Northern Mariana Islands', 'MP', '1-670'),
            array(160, 'Norway', 'NO', '47'),
            array(161, 'Oman', 'OM', '968'),
            array(162, 'Pakistan', 'PK', '92'),
            array(163, 'Palau', 'PW', '680'),
            array(164, 'Panama', 'PA', '507'),
            array(165, 'Papua New Guinea', 'PG', '675'),
            array(166, 'Paraguay', 'PY', '595'),
            array(167, 'Peru', 'PE', '51'),
            array(168, 'Philippines', 'PH', '63'),
            array(169, 'Pitcairn', 'PN', '64'),
            array(170, 'Poland', 'PL', '48'),
            array(171, 'Portugal', 'PT', '351'),
            array(172, 'Puerto Rico', 'PR', '1-787'),
            array(173, 'Qatar', 'QA', '974'),
            array(174, 'Reunion', 'RE', '262'),
            array(175, 'Romania', 'RO', '40'),
            array(176, 'Russian Federation', 'RU', '7'),
            array(177, 'Rwanda', 'RW', '250'),
            array(178, 'Saint Kitts and Nevis', 'KN', '1-869'),
            array(179, 'Saint Lucia', 'LC', '1-758'),
            array(180, 'Saint Vincent and the Grenadines', 'VC', '1-784'),
            array(181, 'Samoa', 'WS', '685'),
            array(182, 'San Marino', 'SM', '378'),
            array(183, 'Sao Tome and Principe', 'ST', '239'),
            array(184, 'Saudi Arabia', 'SA', '966'),
            array(185, 'Senegal', 'SN', '221'),
            array(186, 'Seychelles', 'SC', '248'),
            array(187, 'Sierra Leone', 'SL', '232'),
            array(188, 'Singapore', 'SG', '65'),
            array(189, 'Slovakia (Slovak Republic)', 'SK', '421'),
            array(190, 'Slovenia', 'SI', '386'),
            array(191, 'Solomon Islands', 'SB', '677'),
            array(192, 'Somalia', 'SO', '252'),
            array(193, 'South Africa', 'ZA', '27'),
            array(194, 'South Georgia and the South Sandwich Islands', 'GS', '500'),
            array(195, 'Spain', 'ES', '34'),
            array(196, 'Sri Lanka', 'LK', '94'),
            array(197, 'Saint Helena, Ascension and Tristan da Cunha', 'SH', '290'),
            array(198, 'St. Pierre and Miquelon', 'PM', '508'),
            array(199, 'Sudan', 'SD', '249'),
            array(200, 'Suriname', 'SR', '597'),
            array(201, 'Svalbard and Jan Mayen Islands', 'SJ', '47'),
            array(202, 'Swaziland', 'SZ', '268'),
            array(203, 'Sweden', 'SE', '46'),
            array(204, 'Switzerland', 'CH', '41'),
            array(205, 'Syrian Arab Republic', 'SY', '963'),
            array(206, 'Taiwan', 'TW', '886'),
            array(207, 'Tajikistan', 'TJ', '992'),
            array(208, 'Tanzania, United Republic of', 'TZ', '255'),
            array(209, 'Thailand', 'TH', '66'),
            array(210, 'Togo', 'TG', '228'),
            array(211, 'Tokelau', 'TK', '690'),
            array(212, 'Tonga', 'TO', '676'),
            array(213, 'Trinidad and Tobago', 'TT', '1-868'),
            array(214, 'Tunisia', 'TN', '216'),
            array(215, 'Turkey', 'TR', '90'),
            array(216, 'Turkmenistan', 'TM', '993'),
            array(217, 'Turks and Caicos Islands', 'TC', '1-649'),
            array(218, 'Tuvalu', 'TV', '688'),
            array(219, 'Uganda', 'UG', '256'),
            array(220, 'Ukraine', 'UA', '380'),
            array(221, 'United Arab Emirates', 'AE', '971'),
            array(222, 'United Kingdom', 'GB', '44'),
            array(223, 'United States', 'US', '1'),
            array(224, 'United States Minor Outlying Islands', 'UM', '246'),
            array(225, 'Uruguay', 'UY', '598'),
            array(226, 'Uzbekistan', 'UZ', '998'),
            array(227, 'Vanuatu', 'VU', '678'),
            array(228, 'Vatican City State (Holy See)', 'VA', '379'),
            array(229, 'Venezuela', 'VE', '58'),
            array(230, 'Vietnam', 'VN', '84'),
            array(231, 'Virgin Islands (British)', 'VG', '1-284'),
            array(232, 'Virgin Islands (U.S.)', 'VI', '1-340'),
            array(233, 'Wallis and Futuna Islands', 'WF', '681'),
            array(234, 'Western Sahara', 'EH', '212'),
            array(235, 'Yemen', 'YE', '967'),
            array(236, 'Serbia', 'RS', '381'),
            array(238, 'Zambia', 'ZM', '260'),
            array(239, 'Zimbabwe', 'ZW', '263'),
            array(240, 'Aaland Islands', 'AX', '358'),
            array(241, 'Palestine', 'PS', '970'),
            array(242, 'Montenegro', 'ME', '382'),
            array(243, 'Guernsey', 'GG', '44-1481'),
            array(244, 'Isle of Man', 'IM', '44-1624'),
            array(245, 'Jersey', 'JE', '44-1534'),
            array(247, 'Curaçao', 'CW', '599'),
            array(249, 'Kosovo', 'XK', '383')
            );
    }

}
